import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import NavBar from '@components/NavBar';

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="lg">

          <Typography variant="h3" style={{ color: "white", marginBottom: "1rem" }}>
            About us
          </Typography>
          <Typography variant="h4" style={{ color: "white", marginBottom: "1rem"  }}>
            Hi! I'm Nicole, a front-end web developer from NAIT.
          </Typography>
          <Typography variant="h4" style={{ color: "white", marginBottom: "1rem"  }}>
            I'm currently doing this as a personal project of mine since I'm passionate about Dota 2.
          </Typography>
          <Typography variant="h4" style={{ color: "white" }}>
            Huge thanks to OpenDota API (25.0.0) for creating this Dota API Link: https://docs.opendota.com/
          </Typography>
        </Container>

    </div>
  )
}
