import Head from "next/head";

import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";

import AgencyCard from "@components/AgencyCard";
import NavBar from "@components/NavBar";

import { useEffect, useState } from "react";

import { getHeroes } from "@utils/api/heroes";


export default function Home() {
  const [heroesData, setHeroesData] = useState([]);

  useEffect(() => {
    getHeroes().then((data) => {
      // console.log(data);
      setHeroesData(data);
    });
  }, []);

  return (
    <div>
      <Head>
        <title>Dota Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Container sx={{ paddingTop: 2 }} component="main" maxWidth="xs">
        {/* <Typography variant="h3">Dota Heroes</Typography> */}

        <Box
          sx={{
            marginTop: 2,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          {heroesData.map((hero) => {
            // Clean hero name for the image URL
            const heroName = hero.name.replace("npc_dota_hero_", "");

            // Dota 2 CDN URL
            const imgURL = `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${heroName}.png`;

            return (
              <AgencyCard
                key={hero.id}
                id={hero.id}
                localized_name={hero.localized_name}
                imageUrl={imgURL}
              />
            );
          })}
        </Box>
      </Container>
    </div>
  );
}