import Head from "next/head";

import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import { Grid } from "@mui/material";
import AgencyCard from "@components/AgencyCard";
import NavBar from "@components/NavBar";

import { useEffect, useState } from "react";

import { getHeroes } from "@utils/api/heroes";


export default function Home() {
  const [heroesData, setHeroesData] = useState([]);

  useEffect(() => {
    getHeroes().then((data) => {
      // console.log(data);
      setHeroesData(data);
    });
  }, []);

  return (
    <div>
      <Head>
        <title>Dota Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Box sx={{backgroundColor: "#0d1117"}}>
      <Container sx={{ paddingTop: 2 }} component="main" maxWidth="lg">
        {/* <Typography variant="h3">Dota Heroes</Typography> */}

        <Grid container spacing={5} justifyContent="center">
          {heroesData.map((hero) => {
            // Clean hero name for the image URL
            const heroName = hero.name.replace("npc_dota_hero_", "");

            // Dota 2 CDN URL
            const imgURL = `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${heroName}.png`;

            return (
              <Grid item key={hero.id}>
              <AgencyCard
                key={hero.id}
                id={hero.id}
                localized_name={hero.localized_name}
                imageUrl={imgURL}
              />
              </Grid>
            );
          })}
        </Grid>
      </Container>
      </Box>
    </div>
  );
}